version: 2.1

orbs:
  maven: circleci/maven@1.3

executors:
  openjdk18:
    docker:
      - image: cimg/openjdk:18.0

jobs:
  test:
    executor: openjdk18
    steps:
      - checkout
      - run: mvn test
  build:
    executor: openjdk18
    steps:
      - checkout
      - run: mvn clean compile

workflows:
  verify:
    jobs:
      - test
      - build